### PR TITLE
Support special chars

### PR DESCRIPTION
**Pull request by apiraino**
Hi @cyplo here's the code we've done together. Basically just some copy and paste, I am aware that this patch will badly decrease the global quality of your codebase :-) We'll think of something in a future refactor.

Please have a look at the code at your leisure, the CI passed (on my fork).

Thanks for the pairing session, it was great! :+1:

### CODE REVIEW

**Comment by cyplo** [comment]
Will take a look a bit later, thank you so much ! :)

**Comment by apiraino** [comment]
Also, when you have a chance, try giving the CI another spin; it failed when decompressing a file remotely downloaded:

```
The command "cargo test" exited with 0.
0.67s$ ./ci/upload-coverage-data.sh
~/build/cyplo/genpass ~/build/cyplo/genpass
--2018-05-23 10:25:45--  https://github.com/SimonKagstrom/kcov/archive/master.tar.gz
Resolving github.com (github.com)... 192.30.253.113, 192.30.253.112
Connecting to github.com (github.com)|192.30.253.113|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://codeload.github.com/SimonKagstrom/kcov/tar.gz/master [following]
--2018-05-23 10:25:46--  https://codeload.github.com/SimonKagstrom/kcov/tar.gz/master
Resolving codeload.github.com (codeload.github.com)... 192.30.255.120, 192.30.255.121
Connecting to codeload.github.com (codeload.github.com)|192.30.255.120|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 301845 (295K) [application/x-gzip]
Saving to: ‘master.tar.gz’
100%[======================================>] 301,845     1.87MB/s   in 0.2s   
2018-05-23 10:25:46 (1.87 MB/s) - ‘master.tar.gz’ saved [301845/301845]
gzip: stdin: decompression OK, trailing garbage ignored
tar: Child returned status 2
tar: Error is not recoverable: exiting now
```

I've downloaded that file and it looked ok :-/

**Comment by cyplo** [comment]
Heya, I've made the coverage data upload not fail the build if it fails itself, the change is on master. 
Could you rebase on top of master, or merge master into your branch ? Should make it green. Thanks !

**Comment by cyplo** [comment]
Actually found out that I can do that to your branch myself ;)

**Comment by apiraino** [comment]
great, thank you!

**Pull request merged**
